### ISSUE TITLE
Gamepad input is broken in restricted axes mode

### ISSUE THREAD

**Issue by lachs0r** [laochailan/taisei#55] opened 2017-02-15 03:34 UTC
Right now, gamepad input easily gets stuck in a direction when using analog axes.

**Comment by Akaricchi** [comment] 2017-09-19 21:35
Please test d9611b0831f69a591c1a74a872739d1c93472875 and see if that fixes anything for you. You might also want to increase the deadzone a bit if you're getting noisy inputs.

**Comment by Akaricchi** [comment] 2017-10-01 04:47
I'm closing this, seems like nobody has been able to reproduce this since the gamepad code rewrite.

**Closed by Akaricchi** 2017-10-01 04:47 UTC
